### ISSUE TITLE
GET does not support data schemas

### ISSUE THREAD

**Issue by oliyh** [frankiesardo/pedestal-swagger#15]
A GET request with a `body` or `formData` does not work properly. Whilst strange, they are supported in HTTP with the caveat that they should not affect the behaviour of the request.

Example handler:
```clojure
(swagger/defhandler foo
  {:summary "Does a GET request that expects a body"
   :parameters {:body {:foo s/Str}}
   :responses {200 nil}}
  [_]
  {:status 200 :headers {} :body "You'll not get this far"})
```

Several things happen with a handler like this:
1. Swagger UI ignores the Content-Type and always sends `application/x-www-form-urlencoded`
2. Jetty / Pedestal ignore the body
3. pedestal-swagger attempts to match the body to the schema and fails, returning a 400 as it would for any input that does not match the schema

According to http://stackoverflow.com/questions/978061/http-get-with-request-body:
> Yes, you can send a request body with GET but it should not have any meaning. If you give it meaning by parsing it on the server and changing your response based on its contents you're violating the HTTP/1.1 spec.

I think it is correct behaviour that the schema check fails, because we should be ignoring the body and the contract of Swagger is that everything given to the handlers has already passed the schema check.

**Comment by frankiesardo** [comment]
You're right, the error might be confusing `"body-params": "(not (map? nil))"`. But the swagger documentation associated to an endpoint is method unaware (foo could be both a post or a get) https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#path-item-object so if the behaviour of Jetty is to ignore the body for gets there's little we can do at the swagger level.

Even pedestal itself is already one layer of abstraction on top of this problem, since it can depend on jetty, tomcat, immutant, etc. Maybe on those other server implementations the get-with-body works, and swagger schema check happily pass.

**Comment by oliyh** [comment]
You could add a generic error to the response when a body schema is supplied for a GET request i.e.
```clojure
{
  "error": {
    "body-params": "(not (map? nil))",
    "body": "body is ignored for GET requests"
  }
}
```

This would mean that the same response (400) is always returned for a given request, in accordance with HTTP 1.1. If some web containers allow it, they could conceivably return 200 or 400 depending on whether the body matches the schema or not, which violates HTTP 1.1.

This would also give consistency across web containers, as they would always error, which is maybe better than it just working on some and not on others.
